### ISSUE TITLE
help mee plzz ! z390i + radeon vii + i9 9900k 

### ISSUE THREAD

**Issue by galaran26** [xlanor/asus-z390i-opencore#5]
Hello!
I use a specification similar to yours.
But I am a very biginer for getting down.
Personally, now in use catalina only 
I would like to inquire if I am going to update.
Now i have done usb
Then try to mount EFI and open mount by dragging your files.
But it can't boot and show logo mac error ...
Please explain me in a simple way. I have been with this for 5 days.
Or am I doing it the wrong way? Thanks for the answer in advance.

Spec
-i9 9900k
-aorus z390i 
- radeon vii 

T______T

**Comment by xlanor** [comment]
I suggest you read the opencore guide in detail, and try to understand what you're doing and how to debug your hackintosh. Run it in verbose mode and see what pops up.

Maintaining a hack down the line is probably not going to be easy and so it's better to get started with it now rather than later.
