### ISSUE TITLE
RX 580 stucked on HID: legacy shim 2

### ISSUE THREAD

**Issue by lvxianchao** [xlanor/asus-z390i-opencore#8]
Hello and thank you for the EFI!

But I'm having a bit of a problem with the graphics card.

My video card is RX580 and if I use iGpu, when outputting two 4K@60hz at the same time, the HDMI one can only reach 30HZ.

If I use the RX580, it gets stuck at: `HID: legacy shim 2` when booting.

I don't think this has anything to do with the USB interface, because everything is fine when the graphics card is not plugged in.

Do you know what is the reason for this?

I use a translator to translate Chinese into English, there may be some places inaccurate expression, please forgive me.

![WechatIMG2](https://user-images.githubusercontent.com/22412818/137912300-778830e9-e71d-4453-8610-fe96939ff8b7.jpeg)

**Comment by xlanor** [comment]
这个我不太清楚。我用的是 6800xt
以前我用rx580时, 插进去就好了。

我建议你看看一下这个网络自己建一个 config。
我这个config不适合直接copy+paste就行。

**Comment by xlanor** [comment]
@lvxianchao 

English translation:

I'm not sure. I use an rx6800xt. My RX580 build on catalina was plug and play.

I suggest you read the dortania guide and build your own config. This repository is NOT meant to be used as a plug and play. Merely as a source of reference.

https://dortania.github.io/getting-started/

**Comment by xlanor** [comment]
If I were you I would check  agdpmod=pikera - this particular flag is needed for navi 21. You are not on navi 21.
However, maintaining a hackintosh means you will run into more of these problems. Building your own config is the best way to understand what you need to change and maintain.

**Comment by lvxianchao** [comment]
哦嗨，原来可以说中文。

OK，感谢回复！我这边按照 OC 文档去搞了。

**Comment by xlanor** [comment]
没问题！ OC的却写到很清楚，应改是没什么问题的
